services:
  kamilem:
    container_name: kamilem
    image: image_kamilem
    build: .
    ports:
      - "8002:80"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    external: true
